### ISSUE TITLE
A couple of suggestions

### ISSUE THREAD

**Issue by SandroVA** [loldudester/Emojiscape#1]
**Misc Icons - Both without im**
If possible I'd like misc icon to have an additional dropdown menu option that removes "im" from the icon list; because it's the only short trigger that has another meaning (the player can be talking about themselves).

https://i.imgur.com/HqzMjav.png

**Removing round brackets around icon**
pretty self explanatory.

**Comment by Hannah-GBS** [comment]
For the first suggestion. you can do this yourself by editing the `emojiscape.properties` file in your `.runelite` directory. Removing the trigger from the Misc Triggers - Short section (so it reads `IRONMAN.ShortTrigger=`) should disable it (or you could change it to something else.

As for the second suggestion, I can for sure look into an option for that.

**Comment by SandroVA** [comment]
Hey thanks for the response. I'm not sure I understand how to get to emojiscape properties. 
https://i.imgur.com/ymFWUNP.png

**Comment by Hannah-GBS** [comment]
The `.runelite` folder is separate to the installation folder. You should be able to find it if you put `%userprofile%\.runelite` into Windows Run (Winkey+R)

**Comment by Hannah-GBS** [comment]
This was added in dba2c379d2753c3383fc0c4bea1db5b30b0a6550
